// @generated by protoc-gen-es v1.4.2 with parameter "target=js+dts"
// @generated from file blog/v1/posts.proto (package blog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message blog.v1.CreatePostRequest
 */
export const CreatePostRequest = proto3.makeMessageType(
  "blog.v1.CreatePostRequest",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message blog.v1.CreatePostResponse
 */
export const CreatePostResponse = proto3.makeMessageType(
  "blog.v1.CreatePostResponse",
  [],
);

/**
 * @generated from message blog.v1.Post
 */
export const Post = proto3.makeMessageType(
  "blog.v1.Post",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message blog.v1.ListPostsRequest
 */
export const ListPostsRequest = proto3.makeMessageType(
  "blog.v1.ListPostsRequest",
  [],
);

/**
 * @generated from message blog.v1.ListPostsResponse
 */
export const ListPostsResponse = proto3.makeMessageType(
  "blog.v1.ListPostsResponse",
  () => [
    { no: 1, name: "posts", kind: "message", T: Post, repeated: true },
  ],
);

/**
 * @generated from message blog.v1.DeletePostRequest
 */
export const DeletePostRequest = proto3.makeMessageType(
  "blog.v1.DeletePostRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message blog.v1.DeletePostResponse
 */
export const DeletePostResponse = proto3.makeMessageType(
  "blog.v1.DeletePostResponse",
  [],
);

