// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file blog/v1/posts.proto (package blog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePostRequest, CreatePostResponse, DeletePostRequest, DeletePostResponse, ListPostsRequest, ListPostsResponse } from "./posts_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service blog.v1.BlogService
 */
export declare const BlogService: {
  readonly typeName: "blog.v1.BlogService",
  readonly methods: {
    /**
     * @generated from rpc blog.v1.BlogService.CreatePost
     */
    readonly createPost: {
      readonly name: "CreatePost",
      readonly I: typeof CreatePostRequest,
      readonly O: typeof CreatePostResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.v1.BlogService.ListPosts
     */
    readonly listPosts: {
      readonly name: "ListPosts",
      readonly I: typeof ListPostsRequest,
      readonly O: typeof ListPostsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.v1.BlogService.DeletePost
     */
    readonly deletePost: {
      readonly name: "DeletePost",
      readonly I: typeof DeletePostRequest,
      readonly O: typeof DeletePostResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

