// @generated by protoc-gen-es v1.4.2 with parameter "target=js+dts"
// @generated from file blog/v1/posts.proto (package blog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message blog.v1.CreatePostRequest
 */
export declare class CreatePostRequest extends Message<CreatePostRequest> {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  constructor(data?: PartialMessage<CreatePostRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.CreatePostRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePostRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePostRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePostRequest;

  static equals(a: CreatePostRequest | PlainMessage<CreatePostRequest> | undefined, b: CreatePostRequest | PlainMessage<CreatePostRequest> | undefined): boolean;
}

/**
 * @generated from message blog.v1.CreatePostResponse
 */
export declare class CreatePostResponse extends Message<CreatePostResponse> {
  constructor(data?: PartialMessage<CreatePostResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.CreatePostResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePostResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePostResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePostResponse;

  static equals(a: CreatePostResponse | PlainMessage<CreatePostResponse> | undefined, b: CreatePostResponse | PlainMessage<CreatePostResponse> | undefined): boolean;
}

/**
 * @generated from message blog.v1.Post
 */
export declare class Post extends Message<Post> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  constructor(data?: PartialMessage<Post>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.Post";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Post;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Post;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Post;

  static equals(a: Post | PlainMessage<Post> | undefined, b: Post | PlainMessage<Post> | undefined): boolean;
}

/**
 * @generated from message blog.v1.ListPostsRequest
 */
export declare class ListPostsRequest extends Message<ListPostsRequest> {
  constructor(data?: PartialMessage<ListPostsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.ListPostsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPostsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPostsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPostsRequest;

  static equals(a: ListPostsRequest | PlainMessage<ListPostsRequest> | undefined, b: ListPostsRequest | PlainMessage<ListPostsRequest> | undefined): boolean;
}

/**
 * @generated from message blog.v1.ListPostsResponse
 */
export declare class ListPostsResponse extends Message<ListPostsResponse> {
  /**
   * @generated from field: repeated blog.v1.Post posts = 1;
   */
  posts: Post[];

  constructor(data?: PartialMessage<ListPostsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.ListPostsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPostsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPostsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPostsResponse;

  static equals(a: ListPostsResponse | PlainMessage<ListPostsResponse> | undefined, b: ListPostsResponse | PlainMessage<ListPostsResponse> | undefined): boolean;
}

/**
 * @generated from message blog.v1.DeletePostRequest
 */
export declare class DeletePostRequest extends Message<DeletePostRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<DeletePostRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.DeletePostRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeletePostRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeletePostRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeletePostRequest;

  static equals(a: DeletePostRequest | PlainMessage<DeletePostRequest> | undefined, b: DeletePostRequest | PlainMessage<DeletePostRequest> | undefined): boolean;
}

/**
 * @generated from message blog.v1.DeletePostResponse
 */
export declare class DeletePostResponse extends Message<DeletePostResponse> {
  constructor(data?: PartialMessage<DeletePostResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "blog.v1.DeletePostResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeletePostResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeletePostResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeletePostResponse;

  static equals(a: DeletePostResponse | PlainMessage<DeletePostResponse> | undefined, b: DeletePostResponse | PlainMessage<DeletePostResponse> | undefined): boolean;
}

